### ISSUE TITLE
启动前端，出现代理错误， 不清楚什么原因

### ISSUE THREAD

**Issue by gogov5** [byteblogs168/theme-react-sakura#1]
Proxy error: Could not proxy request /api/blog/posts/weight/v1/list?page=1&size=3 from localhost:3000 to https://127.0.0.1/:8086.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

谢谢

**Comment by gogov5** [comment]
package.json 中配置 为 "proxy": "https://127.0.0.1:8086",   是否正确？

**Comment by by05021** [comment]
/src/lib/axios.js中 修改请求前缀了没

**Comment by by05021** [comment]
配置后重新启动服务

**Comment by gogov5** [comment]
> 配置后重新启动服务

配置重启服务后好了，同样也是忘记了 端口号  ：8086   感谢
